### ISSUE TITLE
Voting Buttons

### ISSUE THREAD

**Issue by GIVEMEARUNFORMYMONEY** [ccrama/Slide-iOS#237]
Using the up/downvote button before opening the post sometimes doesn't register when opening a post so the preview can show you upvoted it but in post you can also downvote it.

**Comment by ccrama** [comment]
Just to confirm, if you upvote in the list view and then enter comments, it will show as not voted? What happens if you pull to refresh on that page?

**Comment by GIVEMEARUNFORMYMONEY** [comment]
Refreshing changes the vote to whatever you voted for on the list view. Addressing your first point: the vote inside the post seems to count on the total upvote mark whereas the list view one doesn't. It's a little confusing to me. https://gfycat.com/FoolishOilyBergerpicard

**Comment by ccrama** [comment]
Your other issue is actually because slide doesn't kill the last comment view, and you opened the same view with the same state over again. As for the voting issue, I cannot reproduce this but what I think is happening is the vote state through the app that I keep is updated only after a successful request, and the time between when you click upvote and open the post is too low for the request to complete

**Comment by ccrama** [comment]
I don't believe this is an issue anymore, feel free to re-open if it surfaces again!
