### ISSUE TITLE
Allow user to hide the floating menu button

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#333]
Wanted to start a conversation about this. It's cool to have the floating button, but personally if I have the menu bars set to hide automatically, it's because I don't want any UI on top of the content at all. I'm advocating for either removing that button or allowing the user to choose if they want it.

**Comment by ccrama** [comment]
What if we merged it with the hiding FAB option? Would that be too confusing?

**Comment by colejd** [comment]
I think that should be a separate thing.

**Comment by WickedColdfront** [comment]
What about removing the floating button and replacing it with button(s) in the bottom menu bar?

**Comment by ccrama** [comment]
@WickedColdfront that's bad UX, the user expects bottom buttons to open a new "pane", like the App Store. But on iPads, I'm planning on expanding the menu bar

**Comment by WickedColdfront** [comment]
@ccrama you definitely bring up a good point.  That said, there are some examples of bottom buttons not opening a new pane in native iOS apps. In the calendar app there’s a button which brings up a menu to switch between calendars and in the Podcast app there are buttons to interact with the selected podcast (pause/resume/skip).  

I think a “more” button which would show options relevant to the screen the user is on would be useful.  That way instead of picking one function at a time (like the current FAB implementation), users could quickly get to all relevant functions.
