### ISSUE TITLE
Refreshing subreddit will only load limited numbers of posts

### ISSUE THREAD

**Issue by lavo27** [ccrama/Slide-iOS#408]
Build 1.0.3. 
Iphone 7 plus
IOS 11.4.1

**Comment by david-me** [comment]
This has happened to me a few times when browsing the frontpage. [Here’s](
https://nextcloud.apps.davidm.me/index.php/s/aHwiYAWKLNpRiy6) a screencast of it happening to me. I don’t know if it’s related, but after that I went to r/all and after scrolling down it a lot the app crashed, and when I reopened the app, the problem was gone

**Comment by lavo27** [comment]
Screencast of my issue.

![issue](https://user-images.githubusercontent.com/6656232/44294593-476aa680-a2cc-11e8-887a-07eaa9273ad2.gif)
