### ISSUE TITLE
Poor scrolling performance 

### ISSUE THREAD

**Issue by SuperTachyon** [ccrama/Slide-iOS#436]
The app stutters when scrolling in both subreddit view and comments. In contrast, Apollo is much smoother.

**Comment by colejd** [comment]
Believe me -- we know haha. I've been pushing for performance for a long time. We'd love help (always do) if anyone has ideas for performance enhancements.

For posterity's sake, I'll list some stuff that is causing stuttering that we're aware of:

1. `LinkCellView` and its subclasses are currently too expensive to create. You'll notice that as you scroll through posts, the stuttering will eventually stop; that's because the system has reached a point where it is purely recycling cells rather than making new ones. Perhaps we can somehow preallocate a bunch of these?

2. Possible Auto Layout constraint churn in `LinkCellView` and its subclasses. Once Xcode 10 is out of beta we'll be getting a really nice new profiler tool to help us figure this one out.

3. `SingleSubredditViewController` implements a custom waterfall layout to do multi column mode. The way this is implemented means that we need to know the height of each cell in advance. That means we're doing some hackery to produce this measurement which may contribute to the lag.

4. Images in post previews are full resolution. We plan on updating SDWebImage soon (#429) to implement a feature that will dramatically reduce memory consumption.

**Comment by djjcast** [comment]
Another possible issue could be using `NSMutableAttributedString` - I've read that they are expensive to create and require work to be done on the main thread when created.

**Comment by ccrama** [comment]
I cache all that when it first loads, they are actually not created at
scroll time.

**Comment by ccrama** [comment]
v3.0 improves this a lot, and we have gotten a lot of feedback that it is working very well now. Closing this!
