### ISSUE TITLE
Implement swipe gestures for posts

### ISSUE THREAD

**Issue by colejd** [ccrama/Slide-iOS#465]
We could easily implement this by incorporating a library like [SwipeCellKit](https://github.com/SwipeCellKit/SwipeCellKit).

**Comment by djjcast** [comment]
What do you think about something like this?: https://github.com/djjcast/Slide-iOS/commit/a7f2479cc9b52c109a359b5064c5f76ce9049ca7

The change allows the user to swipe on a post title to vote. You'll see [this progress animation](https://i.imgur.com/HV09qsb.jpg) when swiping to the right and [this progress animation](https://i.imgur.com/h260R6m.jpg) when swiping to the left. A vote is registered when the progress animation reaches 100%.

It's just an idea and proof of concept so feel free to let me know what you think. I personally felt like the overlay animation was awkward at first but after using it for a while it started to feel more natural.

**Comment by ccrama** [comment]
That is super interesting @djjcast , I think making the bar horizontal would make the UI fit a little better but the concept is great! That would solve a lot of issues with a new implementation (namely, how it would work in multicolumn mode and how it would work with a UICollectionView). If you would like any help or input on that I would be happy to help :D

**Comment by djjcast** [comment]
Yeah, the circular animation does seem out of place. I originally tried to make the animation show "behind" the title but ran into a constraint/format issue - also, it didn't look uniform since post titles are different sizes. This update shows the animation as an overlay of the entire cell and includes support for hide/save: https://github.com/djjcast/Slide-iOS/commit/61d7f0b1cf993319d198262ec746f8e3d920ca0c

Demo videos:
https://i.imgur.com/Mj49BCU.mp4
https://i.imgur.com/1tP6MKw.mp4

Feel free to expand on the idea if you have any other suggestions. I was thinking it might look nice and be helpful if there was an icon on the animation that updated depending on the mode (upvote/downvote/save/hide).

**Comment by djjcast** [comment]
Sure, no problem, PR submitted. See https://github.com/ccrama/Slide-iOS/pull/467.

**Comment by ccrama** [comment]
I think this is more or less done, I did a lot of work on the gesture recognition and animations. What do you think @djjcast @colejd ?

**Comment by colejd** [comment]
There are some remaining issues with resetting the gesture and swiping from the edges, but it looks great so far!

**Comment by djjcast** [comment]
There are a couple issues that weren't present at this commit point: https://github.com/ccrama/Slide-iOS/tree/faec8d243ea236336b5ebc327106294fe5299092

First, submission swiping now causes a crash in comments view. Changing https://github.com/ccrama/Slide-iOS/blob/59a706a91dd480532a188a8f48c9e1adc025d5ab/Slide%20for%20Reddit/LinkCellView.swift#L527 to `let translation = recognizer.translation(in: recognizer.view!)` seems to resolve this issue after some quick testing.

Second, submission swiping from the edge of the cell seems broken. Although, I'm not sure if this behavior is intentional: https://i.imgur.com/mPpebBe.mp4 (swipe from left edge, right edge, left off-center, and right off-center, respectively)

**Comment by colejd** [comment]
Noted on both points. We can actually improve the `isVerticalGesture` method a little bit by reusing some of our code in `BottomMenuPresentationController`. That uses the angle of the gesture rather than comparing x and y directly, which should let specify more accurate "dead zones". Directly comparing x and y in the way that we currently do could be inaccurate if there's any amount of curvature when the user swipes.

**Comment by colejd** [comment]
@ccrama I think we're done as of 5d15ec3!

**Comment by ccrama** [comment]
It is!
