### ISSUE TITLE
Comments can be upvoted by swiping but the animation is missing 

### ISSUE THREAD

**Issue by incIined** [ccrama/Slide-iOS#68]
Right now, you swipe and there's no indication you upvoted other than the comment score changing and turning orange.

**Comment by ccrama** [comment]
I am actually going to be removing that gesture in the next version, that was a feature of the old comment system but I think the tap for menu is easy enough to do. What are your thoughts?

**Comment by incIined** [comment]
Personally I like swiping but only if I can customize the swipe actions

**Comment by jglass071** [comment]
I don’t think I would have used the feature too much. I used it in Beam and when swiping it often did the wrong thing e.g. I would swipe too much or too little very often. Might use it if there is **one action per direction of swipe** (upvote left, reply right?) so I can’t get it wrong. Don’t know how it’s implemented in Slide however because I can’t sign in but there’s an idea.

**Comment by ccrama** [comment]
Removed in favor of swipe to close from anywhere, I think that is a more useful action for everyone. If you have any suggestions, though, feel free to comment below!
