### ISSUE TITLE
Reloading comments after network issue

### ISSUE THREAD

**Issue by flostellbrink** [ccrama/Slide-iOS#756]
Hi! I've been running into this issue a lot, due to my bad network connection.
Here is how to reproduce it:

- Open Slide
- Enable airplane mode (to simulate network problem)
- Open a post -> Blue box says "No cached comments found"
- Disable airplane mode (to simulate network recovering)
- Refresh post

Instead of reloading, Slide is still going to try to find cached comments.
The same blue error box reappears.
Even when leaving the post and going back into it, this issue persists.

This looks like the app automatically goes into an offline mode for the post when loading fails. IMO it should also automatically leave that mode, or offer a way to actually try to reload comments.

**Comment by ccrama** [comment]
The issue with this is actually a lot more complicated. When Slide loads the last loaded content (offline data), and I try to access the variables inside the offline objects, the app will crash because of some threading issues with the offline library I'm using. This becomes an issue when I try to access the post ID in order to load comments, as it cannot access the ID without crashing. If I can find a way to access this without a crash, it would be able to load comments even if it is displaying offline data but as a temporary band-aid I have just made it have that popup

**Comment by Owlinated** [comment]
Sorry to hear that. Wish I could help, but I don't even have a mac to play around with.
Best of luck with finding a solution and thanks so much for your hard work!
