### ISSUE TITLE
[Request] please add SF Rounded as a font option

### ISSUE THREAD

**Issue by lwndow** [ccrama/Slide-iOS#851]
Hi,

There is a variant of SF called “Rounded” that was added to Twitterrific for their recent release – it’s great for readability! Please add this as an option for Slide!

Thanks!

**Comment by colejd** [comment]
Hi! I tried to do this, but there doesn't appear to be a way to do it without actually importing the font file from an external source, which would violate Apple's license. I'll look into it, but I'm sorry to say that it's not looking likely.

To be more specific, the different variants of SF are internal to iOS. You can't specify which version of SF you want; you only specify that you _want_ SF, and iOS will pick the variant based on the context. For example, SF Display is selected when you're using SF on an iPhone, and SF Rounded is selected when you're using SF on an Apple Watch. All we can do for now is let you pick SF, which will always default to SF Display internally.

However! We support any font that is installed on the system. If you use another program to install San Francisco Rounded as its own font, you could certainly import it for use that way.

**Comment by colejd** [comment]
Note for future me: I tried dumping all the font names for iOS in Xcode 10/11, the results of which you can find [here](https://gist.github.com/colejd/da040f8656cd3055d0c460464ac9f582). You can theoretically create a UIFont from any of the string names listed (i.e. `UIFont(name: ".SFUIRounded", size: 16)`), but none of the ones I tried seem to work. Further, when you do that, our font selector can't tell the difference between the variants when the name is stored and retrieved, since they all evaluate to the same value externally. I'm forced to conclude that the only way we can really make this happen is by adding SF variants as separate fonts, which would violate Apple's license, so I don't think this is possible for us to do at this time.

**Comment by colejd** [comment]
I found a way! SF Rounded and SF Serif will be available with the next release, as long as you're on iOS 13 :)

See #893 for technical details.
