### ISSUE TITLE
Night mode enables and disables while locking phone

### ISSUE THREAD

**Issue by ccrama** [ccrama/Slide-iOS#897]

**Comment by ccrama** [comment]
Might be an Apple bug...

**Comment by PiwwowPants** [comment]
Does this refer to how `UITraitCollection.current.userInterfaceStyle` briefly changes from .dark (or .light) to .unspecified, then back when locking?
If so, this is because Apple doesn't update night mode as the schedule passes. Instead, the trait collection is re-initialized when any given app stops. So this *should* happen when the device locks (or when the app is backgrounded any other way).

What may be worth looking at is if we are updating the schedule too often. Other than by force when you're first setting night mode, maybe we shouldn't be checking for updates all the time and instead take a note from Apple and only update when the user leaves the app (i see that we are updating all the time, whenever a view is about to be shown?)

**Comment by ccrama** [comment]
Yep, you're exactly right. My solution was to time the changes for a few ms in the future, and check to see if the UIApplication's state is active before changing the theme 169e9440
